[2022-05-24 11:23:26,721] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-23T00:00:00+00:00 [queued]>
[2022-05-24 11:23:26,815] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-23T00:00:00+00:00 [queued]>
[2022-05-24 11:23:26,820] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-24 11:23:26,826] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-24 11:23:26,838] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-24 11:23:26,978] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_books> on 2022-05-23T00:00:00+00:00
[2022-05-24 11:23:27,012] {standard_task_runner.py:52} INFO - Started process 41 to run task
[2022-05-24 11:23:27,070] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'save_books', '2022-05-23T00:00:00+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmp5x92qy9s', '--error-file', '/tmp/tmpnrxe51o_']
[2022-05-24 11:23:27,073] {standard_task_runner.py:77} INFO - Job 33: Subtask save_books
[2022-05-24 11:23:27,326] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.save_books 2022-05-23T00:00:00+00:00 [running]> on host 0f09442c242c
[2022-05-24 11:23:27,659] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=save_books
AIRFLOW_CTX_EXECUTION_DATE=2022-05-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-23T00:00:00+00:00
[2022-05-24 11:23:27,745] {python.py:151} INFO - Done. Returned value was: None
[2022-05-24 11:23:27,788] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=save_books, execution_date=20220523T000000, start_date=20220524T112326, end_date=20220524T112327
[2022-05-24 11:23:28,139] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-24 11:23:28,220] {local_task_job.py:151} INFO - Task exited with return code 0
