[2022-05-23 20:59:54,203] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-22T00:00:00+00:00 [queued]>
[2022-05-23 20:59:54,259] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-22T00:00:00+00:00 [queued]>
[2022-05-23 20:59:54,260] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:59:54,262] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-23 20:59:54,263] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:59:55,550] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_books> on 2022-05-22T00:00:00+00:00
[2022-05-23 20:59:55,663] {standard_task_runner.py:52} INFO - Started process 42 to run task
[2022-05-23 20:59:55,704] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'save_books', '2022-05-22T00:00:00+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmp_pti52kj', '--error-file', '/tmp/tmpp4obg6zu']
[2022-05-23 20:59:55,747] {standard_task_runner.py:77} INFO - Job 24: Subtask save_books
[2022-05-23 21:00:01,985] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.save_books 2022-05-22T00:00:00+00:00 [running]> on host 0f09442c242c
[2022-05-23 21:00:04,841] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=save_books
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-22T00:00:00+00:00
[2022-05-23 21:00:05,177] {python.py:151} INFO - Done. Returned value was: None
[2022-05-23 21:00:05,230] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=save_books, execution_date=20220522T000000, start_date=20220523T205954, end_date=20220523T210005
[2022-05-23 21:00:05,951] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-23 21:00:06,182] {local_task_job.py:151} INFO - Task exited with return code 0
