[2022-05-26 16:11:35,696] {scheduler_job.py:182} INFO - Started process (PID=22) to work on /opt/airflow/dags/books_db.py
[2022-05-26 16:11:35,718] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/books_db.py for tasks to queue
[2022-05-26 16:11:35,723] {logging_mixin.py:104} INFO - [2022-05-26 16:11:35,722] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/books_db.py
[2022-05-26 16:11:48,482] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['book_db']) retrieved from /opt/airflow/dags/books_db.py
[2022-05-26 16:11:48,657] {logging_mixin.py:104} INFO - [2022-05-26 16:11:48,655] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 16:11:48,907] {logging_mixin.py:104} INFO - [2022-05-26 16:11:48,907] {dag.py:2306} INFO - Setting next_dagrun for book_db to 2022-05-25 00:00:00+00:00
[2022-05-26 16:11:49,292] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/books_db.py took 13.612 seconds
[2022-05-26 16:13:23,363] {scheduler_job.py:182} INFO - Started process (PID=29) to work on /opt/airflow/dags/books_db.py
[2022-05-26 16:13:23,366] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/books_db.py for tasks to queue
[2022-05-26 16:13:23,385] {logging_mixin.py:104} INFO - [2022-05-26 16:13:23,385] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/books_db.py
[2022-05-26 16:13:36,647] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['book_db']) retrieved from /opt/airflow/dags/books_db.py
[2022-05-26 16:13:36,950] {logging_mixin.py:104} INFO - [2022-05-26 16:13:36,932] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 16:13:37,125] {logging_mixin.py:104} INFO - [2022-05-26 16:13:37,125] {dag.py:2306} INFO - Setting next_dagrun for book_db to 2022-05-26 00:00:00+00:00
[2022-05-26 16:13:37,340] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/books_db.py took 14.013 seconds
[2022-05-26 17:04:15,165] {scheduler_job.py:182} INFO - Started process (PID=35) to work on /opt/airflow/dags/books_db.py
[2022-05-26 17:04:15,190] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/books_db.py for tasks to queue
[2022-05-26 17:04:15,200] {logging_mixin.py:104} INFO - [2022-05-26 17:04:15,199] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/books_db.py
[2022-05-26 17:04:49,910] {logging_mixin.py:104} INFO - [2022-05-26 17:04:49,867] {timeout.py:36} ERROR - Process timed out, PID: 35
[2022-05-26 17:04:50,050] {logging_mixin.py:104} INFO - [2022-05-26 17:04:49,996] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/books_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/books_db.py", line 12, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/_libs/tslibs/__init__.py", line 30, in <module>
    from .conversion import OutOfBoundsTimedelta, localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 58, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/books_db.py after 30.0s, PID: 35
[2022-05-26 17:04:50,083] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/books_db.py
[2022-05-26 17:04:50,376] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/books_db.py took 35.294 seconds
[2022-05-26 20:33:37,370] {scheduler_job.py:182} INFO - Started process (PID=21) to work on /opt/airflow/dags/books_db.py
[2022-05-26 20:33:37,389] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/books_db.py for tasks to queue
[2022-05-26 20:33:37,414] {logging_mixin.py:104} INFO - [2022-05-26 20:33:37,414] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/books_db.py
[2022-05-26 20:33:43,265] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['book_db']) retrieved from /opt/airflow/dags/books_db.py
[2022-05-26 20:33:43,407] {logging_mixin.py:104} INFO - [2022-05-26 20:33:43,402] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 20:33:43,520] {logging_mixin.py:104} INFO - [2022-05-26 20:33:43,520] {dag.py:2306} INFO - Setting next_dagrun for book_db to 2022-05-26 00:00:00+00:00
[2022-05-26 20:33:43,722] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/books_db.py took 6.448 seconds
[2022-05-26 20:35:56,305] {scheduler_job.py:182} INFO - Started process (PID=33) to work on /opt/airflow/dags/books_db.py
[2022-05-26 20:35:56,339] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/books_db.py for tasks to queue
[2022-05-26 20:35:56,353] {logging_mixin.py:104} INFO - [2022-05-26 20:35:56,348] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/books_db.py
[2022-05-26 20:36:02,584] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['book_db']) retrieved from /opt/airflow/dags/books_db.py
[2022-05-26 20:36:02,785] {logging_mixin.py:104} INFO - [2022-05-26 20:36:02,784] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 20:36:02,856] {logging_mixin.py:104} INFO - [2022-05-26 20:36:02,856] {dag.py:2306} INFO - Setting next_dagrun for book_db to 2022-05-26 00:00:00+00:00
[2022-05-26 20:36:03,033] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/books_db.py took 6.767 seconds
[2022-05-26 20:43:33,521] {scheduler_job.py:182} INFO - Started process (PID=39) to work on /opt/airflow/dags/books_db.py
[2022-05-26 20:43:33,536] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/books_db.py for tasks to queue
[2022-05-26 20:43:33,553] {logging_mixin.py:104} INFO - [2022-05-26 20:43:33,553] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/books_db.py
[2022-05-26 20:44:28,922] {logging_mixin.py:104} INFO - [2022-05-26 20:44:28,904] {timeout.py:36} ERROR - Process timed out, PID: 39
[2022-05-26 20:44:29,049] {logging_mixin.py:104} INFO - [2022-05-26 20:44:28,949] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/books_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/books_db.py", line 12, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/__init__.py", line 51, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/api.py", line 15, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 56, in <module>
    from pandas.core.strings.object_array import ObjectStringArrayMixin
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/strings/__init__.py", line 30, in <module>
    from .base import BaseStringArrayMethods
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/strings/base.py", line 9, in <module>
    class BaseStringArrayMethods(abc.ABC):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/strings/base.py", line 144, in BaseStringArrayMethods
    def _str_isalnum(self):
  File "/usr/local/lib/python3.8/abc.py", line 24, in abstractmethod
    funcobj.__isabstractmethod__ = True
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/books_db.py after 30.0s, PID: 39
[2022-05-26 20:44:29,226] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/books_db.py
[2022-05-26 20:44:29,680] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/books_db.py took 56.321 seconds
[2022-05-26 20:51:34,374] {scheduler_job.py:182} INFO - Started process (PID=23) to work on /opt/airflow/dags/books_db.py
[2022-05-26 20:51:34,378] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/books_db.py for tasks to queue
[2022-05-26 20:51:34,392] {logging_mixin.py:104} INFO - [2022-05-26 20:51:34,391] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/books_db.py
[2022-05-26 20:51:39,362] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['book_db']) retrieved from /opt/airflow/dags/books_db.py
[2022-05-26 20:51:39,471] {logging_mixin.py:104} INFO - [2022-05-26 20:51:39,471] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 20:51:39,628] {logging_mixin.py:104} INFO - [2022-05-26 20:51:39,628] {dag.py:2306} INFO - Setting next_dagrun for book_db to 2022-05-26 00:00:00+00:00
[2022-05-26 20:51:39,773] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/books_db.py took 5.427 seconds
