[2022-05-26 20:52:17,627] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 20:52:17,913] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 20:52:17,927] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 20:52:17,928] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-26 20:52:17,937] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 20:52:18,350] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_books> on 2022-05-25T00:00:00+00:00
[2022-05-26 20:52:18,388] {standard_task_runner.py:52} INFO - Started process 28 to run task
[2022-05-26 20:52:18,610] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'save_books', '2022-05-25T00:00:00+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmp2puwpse2', '--error-file', '/tmp/tmpar7qyck2']
[2022-05-26 20:52:18,620] {standard_task_runner.py:77} INFO - Job 41: Subtask save_books
[2022-05-26 20:52:19,092] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.save_books 2022-05-25T00:00:00+00:00 [running]> on host 0f09442c242c
[2022-05-26 20:52:19,470] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=save_books
AIRFLOW_CTX_EXECUTION_DATE=2022-05-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-25T00:00:00+00:00
[2022-05-26 20:52:19,570] {python.py:151} INFO - Done. Returned value was: None
[2022-05-26 20:52:19,602] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=save_books, execution_date=20220525T000000, start_date=20220526T205217, end_date=20220526T205219
[2022-05-26 20:52:19,968] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-26 20:52:20,077] {local_task_job.py:151} INFO - Task exited with return code 0
