[2022-05-31 19:15:41,125] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-28T00:00:00+00:00 [queued]>
[2022-05-31 19:15:41,145] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-28T00:00:00+00:00 [queued]>
[2022-05-31 19:15:41,146] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:15:41,147] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-31 19:15:41,148] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:15:41,208] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_books> on 2022-05-28T00:00:00+00:00
[2022-05-31 19:15:41,212] {standard_task_runner.py:52} INFO - Started process 40 to run task
[2022-05-31 19:15:41,218] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'save_books', '2022-05-28T00:00:00+00:00', '--job-id', '50', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmpwtn6po0d', '--error-file', '/tmp/tmp91eedn18']
[2022-05-31 19:15:41,220] {standard_task_runner.py:77} INFO - Job 50: Subtask save_books
[2022-05-31 19:15:42,321] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.save_books 2022-05-28T00:00:00+00:00 [running]> on host 7a1d03ce9394
[2022-05-31 19:15:42,455] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=save_books
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T00:00:00+00:00
[2022-05-31 19:15:42,490] {python.py:151} INFO - Done. Returned value was: None
[2022-05-31 19:15:42,504] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=save_books, execution_date=20220528T000000, start_date=20220531T191541, end_date=20220531T191542
[2022-05-31 19:15:42,640] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-31 19:15:42,657] {local_task_job.py:151} INFO - Task exited with return code 0
