[2022-05-31 16:40:37,882] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: book_db.save_books manual__2022-05-31T16:38:08.051690+00:00 [queued]>
[2022-05-31 16:40:37,915] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: book_db.save_books manual__2022-05-31T16:38:08.051690+00:00 [queued]>
[2022-05-31 16:40:37,922] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 16:40:37,924] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-31 16:40:37,925] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 16:40:37,952] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): save_books> on 2022-05-31 16:38:08.051690+00:00
[2022-05-31 16:40:37,966] {standard_task_runner.py:52} INFO - Started process 311 to run task
[2022-05-31 16:40:37,988] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'book_db', 'save_books', 'manual__2022-05-31T16:38:08.051690+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmp_wzt7vyg', '--error-file', '/tmp/tmp4e4k3ogf']
[2022-05-31 16:40:37,994] {standard_task_runner.py:80} INFO - Job 9: Subtask save_books
[2022-05-31 16:40:38,128] {task_command.py:369} INFO - Running <TaskInstance: book_db.save_books manual__2022-05-31T16:38:08.051690+00:00 [running]> on host c713a0714fa8
[2022-05-31 16:40:38,278] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=save_books
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T16:38:08.051690+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-31T16:38:08.051690+00:00
[2022-05-31 16:40:38,470] {python.py:173} INFO - Done. Returned value was: None
[2022-05-31 16:40:38,525] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=save_books, execution_date=20220531T163808, start_date=20220531T164037, end_date=20220531T164038
[2022-05-31 16:40:38,679] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-31 16:40:38,945] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
